services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]

  backend:
    build: backend
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app